---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nposk
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nposk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: nposk
    namespace: kube-system
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: nposk
  annotations:
    kubernetes.io/service-account.name: "nposk"
  namespace: kube-system

#kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep nposk | awk '{print $1}')
