{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sgw.fullname" . }}
  labels:
    {{- include "sgw.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.configMap.data }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end }}