{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sgw.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "sgw.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.spec }}
  spec:
    {{- toYaml .Values.ingress.spec | nindent 4 }}
  {{- end }}
{{- end }}
