apiVersion: v1
kind: Service
metadata:
  name: {{ include "sgw.fullname" . }}
  labels:
    {{- include "sgw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    {{- include "sgw.selectorLabels" . | nindent 4 }}
